#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MOBILE_NOITE.Resource", IsApplication=true)]

namespace MOBILE_NOITE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int estadoXML = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baseline_android_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int baseline_event_seat_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int baseline_face_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ios = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PROJETO = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int XAMARIN = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int AutoComplet = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int AutoCompletXML = 2131099675;
			
			// aapt resource value: 0x7f060002
			public const int IOS = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int android = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ativ4Cadastar = 2131099655;
			
			// aapt resource value: 0x7f060021
			public const int atividade4 = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int atividade_tres = 2131099679;
			
			// aapt resource value: 0x7f060004
			public const int atv4_nome = 2131099652;
			
			// aapt resource value: 0x7f060027
			public const int aut_xml = 2131099687;
			
			// aapt resource value: 0x7f06003b
			public const int bt = 2131099707;
			
			// aapt resource value: 0x7f06003d
			public const int btAlert = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int btAlertOkNo = 2131099710;
			
			// aapt resource value: 0x7f060009
			public const int btPer = 2131099657;
			
			// aapt resource value: 0x7f06003f
			public const int btToast = 2131099711;
			
			// aapt resource value: 0x7f060023
			public const int bt_Passagem = 2131099683;
			
			// aapt resource value: 0x7f060008
			public const int campoNome = 2131099656;
			
			// aapt resource value: 0x7f06001e
			public const int checkbox = 2131099678;
			
			// aapt resource value: 0x7f06002d
			public const int chk_angula = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int chk_c = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int chk_css = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int chk_html = 2131099689;
			
			// aapt resource value: 0x7f060030
			public const int chk_js = 2131099696;
			
			// aapt resource value: 0x7f06002a
			public const int chk_mysql = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int chk_php = 2131099688;
			
			// aapt resource value: 0x7f06002e
			public const int chk_react = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int chk_vue = 2131099695;
			
			// aapt resource value: 0x7f060018
			public const int cidadeCad = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int cidadeForm = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int endCad = 2131099670;
			
			// aapt resource value: 0x7f06000e
			public const int endForm = 2131099662;
			
			// aapt resource value: 0x7f060026
			public const int estado = 2131099686;
			
			// aapt resource value: 0x7f060019
			public const int estadosCad = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int formCadastar = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int img01 = 2131099648;
			
			// aapt resource value: 0x7f060032
			public const int imgAndr = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int imgIos = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int imgv = 2131099697;
			
			// aapt resource value: 0x7f06003a
			public const int lb_sp = 2131099706;
			
			// aapt resource value: 0x7f06003c
			public const int mostra = 2131099708;
			
			// aapt resource value: 0x7f06000a
			public const int mostraPer = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int nomeCadastrado = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int nomeForm = 2131099659;
			
			// aapt resource value: 0x7f060022
			public const int nomePassagem = 2131099682;
			
			// aapt resource value: 0x7f060020
			public const int passagem_tela = 2131099680;
			
			// aapt resource value: 0x7f060035
			public const int rd01 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int rd02 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int rd03 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int rd04 = 2131099704;
			
			// aapt resource value: 0x7f060025
			public const int recebeAtvid4 = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int recebeDados = 2131099684;
			
			// aapt resource value: 0x7f060017
			public const int ruaCad = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int ruaForm = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int senhaAtv4 = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int senhaForm = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int sexoCad = 2131099669;
			
			// aapt resource value: 0x7f06000c
			public const int sexoF = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int sexoM = 2131099661;
			
			// aapt resource value: 0x7f060039
			public const int sp01 = 2131099705;
			
			// aapt resource value: 0x7f060005
			public const int spAtiv4 = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int spForm = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int spinner = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int spinnerxml = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int xamarin = 2131099649;
			
			// aapt resource value: 0x7f060034
			public const int xamrin = 2131099700;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ATIVIDADE2_RADIOBUTTON_IMAGEVIEW = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Atividade4 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Atividade_AlertDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Atividae3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AULAS = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Passagem_Parametro_Tela = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Recebe_Parametro_Tela = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RecebeAtvidade4 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ViewAutoCompletTextView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ViewAutoCompletTextViewXML = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ViewCheckBox = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ViewImageView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ViewRadioButton = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ViewSpinner = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int widgetAula01 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int WiewAlertDialog = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bt_complet = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int bt_completXML = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int bt_spinner = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int bt_spinnerxml = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int estado = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ms_estado = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
